---
- name: Create and Configure a guest VM.
  vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_vmdatacenter }}'
    cluster: '{{ vcenter_vmcluster }}'
    folder: '{{ group_names[-1] | upper }}'
    name: '{{ inventory_hostname | upper }}'
    template: '{{ vm_template }}'
    validate_certs: 'no'
    state: 'poweredon'
    disk:
      - disk1:
        size_gb: '{{ vm_disk1 }}'
        type: '{{ vm_disktype }}'
        datastore: '{{ vm_datastore }}'
      - disk2:
        size_gb: '{{ vm_disk2 }}'
        type: '{{ vm_disktype }}'
        datastore: '{{ vm_datastore }}'
    hardware:
      memory_mb: '{{ vm_memory | int * 1024 }}'
      num_cpus: '{{ vm_cpucount }}'
    networks:
    - name: '{{ vm_network }}'
      ip: '{{ ansible_host }}'
      netmask: '{{ vm_netmask }}'
      gateway: '{{ vm_gateway }}'
      dns_servers: '{{ vm_dns_server }}'
      type: 'static'
    customization:
      hostname: '{{ inventory_hostname | upper }}'
      domain: 'node.{{ datacenter }}.{{ domain }}'
      dns_suffix: '{{ datacenter }}.{{ domain }}'
      dns_servers: '{{ vm_dns_server }}'
      password: '{{ ansible_password }}'
      full_name: '--'
      org_name: '--'
    wait_for_ip_address: 'yes'
  delegate_to: 'localhost'