---
- name: Create and Configure a guest VM
  vmware_guest:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vmdatacenter }}'
    cluster: '{{ vmcluster }}'
    folder: '{{ group_names[0] | upper }}'
    name: '{{ inventory_hostname | upper }}'
    template: '{{ template }}'
    validate_certs: 'no'
    state: 'poweredon'
    disk:
      - disk1:
        size_gb: '{{ disk1 }}'
        type: '{{ disktype }}'
        datastore: '{{ datastore }}'
      - disk2:
        size_gb: '{{ disk2 }}'
        type: '{{ disktype }}'
        datastore: '{{ datastore }}'
    hardware:
      memory_mb: '{{ memory|int * 1024 }}'
      num_cpus: '{{ cpucount }}'
    networks:
    - name: '{{ network }}'
      ip: '{{ ansible_host }}'
      netmask: '{{ netmask }}'
      gateway: '{{ gateway }}'
      dns_servers: '{{ dns_server }}'
      type: 'static'
    customization:
      hostname: '{{ inventory_hostname | upper }}'
      domain: '{{ domain }}'
      dns_suffix: '{{ dns_suffix }}'
      dns_servers: '{{ dns_server }}'
      password: '{{ ansible_password }}'
      full_name: '--'
      org_name: '--'
    wait_for_ip_address: 'yes'
  delegate_to: 'localhost'
