---
- name: Create a folder on VCenter datacenter.
  vcenter_folder:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_vmdatacenter }}'
    folder_name: '{{ group_names[-1] | upper }}'
    folder_type: 'vm'
    state: 'present'
    validate_certs: 'no'
  delegate_to: 'localhost'
  changed_when: false
  failed_when: false
  run_once: true
  no_log: true