---
- name: Create a Customer folder on VCenter datacenter.
  community.vmware.vcenter_folder:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_vmdatacenter }}'
    folder_name: '{{ customer | title }}'
    folder_type: 'vm'
    state: 'present'
    validate_certs: 'no'
  delegate_to: 'localhost'
  changed_when: false
  failed_when: false
  no_log: true

- name: Create a Project folder on VCenter datacenter.
  community.vmware.vcenter_folder:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_vmdatacenter }}'
    parent_folder: '{{ customer | title }}'
    folder_name: '{{ group_names[-1] | title }}'
    folder_type: 'vm'
    state: 'present'
    validate_certs: 'no'
  delegate_to: 'localhost'
  changed_when: false
  failed_when: false
  no_log: true

- name: Create a Group folder on VCenter datacenter.
  community.vmware.vcenter_folder:
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_vmdatacenter }}'
    parent_folder: '{{ customer | title }}/{{ group_names[-1] | title }}'
    folder_name: '{{ group_names[0] | title }}'
    folder_type: 'vm'
    state: 'present'
    validate_certs: 'no'
  delegate_to: 'localhost'
  changed_when: false
  failed_when: false
  no_log: true
