---
- name: Gather guest VM facts from VMware vCenter.
  community.vmware.vmware_guest_info:
    name: '{{ inventory_hostname | upper }}'
    folder: '{{ vcenter_vmdatacenter }}/vm/{{ customer | title }}/{{ group_names[-1] | title }}/{{ group_names[0] | title }}'
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vcenter_vmdatacenter }}'
    validate_certs: 'no'
  delegate_to: 'localhost'
  changed_when: false
  failed_when: false
  register: vmware_facts
  no_log: true

- name: Virtual machines operation.
  block:
    - include: 'folder.yml'
    - include: 'vm.yml'
  when: vmware_facts.instance is not defined
