---
- name: Gather guest VM facts from VMware vCenter
  vmware_guest_facts:
    name: '{{ inventory_hostname|upper }}'
    folder: '{{ vmdatacenter }}/vm/{{ host_group|upper }}'
    hostname: '{{ vcenter_hostname }}'
    username: '{{ vcenter_username }}'
    password: '{{ vcenter_password }}'
    datacenter: '{{ vmdatacenter }}'
    validate_certs: no
  delegate_to: localhost
  changed_when: false
  failed_when: false
  register: facts
  no_log: true

- block:
    - include: 'folder.yml'
    - include: 'create.yml'
    - include: 'edit.yml'
  when: facts.instance is not defined